version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: leang
      POSTGRES_PASSWORD: leang
      POSTGRES_DB: di_mvc
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U leang -d di_mvc']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: nest_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: leang
      RABBITMQ_DEFAULT_PASS: leang
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: